name: Inference Service Unit Testing and Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - master

env:
  DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
  REPO_NAME: ${{secrets.DOCKERHUB_REPO}}

jobs:
  push-image-to-docker-hub:
    #needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        run: | 
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Keycloak Docker image
        run: docker build ./keycloak/docker --tag $DOCKER_USER/$REPO_NAME:keycloak
      - name: Push the Keycloak Docker image
        run: docker push $DOCKER_USER/$REPO_NAME:keycloak  
      - name: Build the Inference Service Docker image
        run: docker build . --file docker/Dockerfile --tag $DOCKER_USER/$REPO_NAME:inference-service
      - name: Push the Inference Service Docker image
        run: docker push $DOCKER_USER/$REPO_NAME:inference-service
